//tag::ref-doc[]
= Gemfire Sink

The Gemfire sink allows one to write message payloads to a Gemfire server.

To enable SSL communication between Geode Sink and the Geode cluster you need to provide the URIs of the
Keystore and Truststore files using the `gemfire.security.ssl.keystore-uri` and `gemfire.security.ssl.truststore-uri` properties.
(If a single file is ued for both stores then point both URIs to it).

== Input

=== Headers

* `content-type: text/plain`

=== Payload

* `String`

=== Headers

* `content-type: application/x-java-serialized-object`

=== Payload

* `java.io.Serializable`

== Output

N/A

== Options

The **$$gemfire$$** $$sink$$ has the following options:

//tag::configuration-properties[]
$$gemfire.json$$:: $$Indicates if the Gemfire region stores json objects as native Gemfire PdxInstance$$ *($$Boolean$$, default: `$$false$$`)*
$$gemfire.key-expression$$:: $$SpEL expression to use as a cache key$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.pool.connect-type$$:: $$Specifies connection type: 'server' or 'locator'.$$ *($$ConnectType$$, default: `$$<none>$$`, possible values: `locator`,`server`)*
$$gemfire.pool.host-addresses$$:: $$Specifies one or more Gemfire locator or server addresses formatted as [host]:[port].$$ *($$InetSocketAddress[]$$, default: `$$<none>$$`)*
$$gemfire.pool.subscription-enabled$$:: $$Set to true to enable subscriptions for the client pool. Required to sync updates to the client cache.$$ *($$Boolean$$, default: `$$false$$`)*
$$gemfire.region.region-name$$:: $$The region name.$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.password$$:: $$The cache password.$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.ciphers$$:: $$Configures the SSL ciphers used for secure Socket connections as an array of valid cipher names.$$ *($$String$$, default: `$$any$$`)*
$$gemfire.security.ssl.keystore-type$$:: $$Identifies the type of Keystore used for SSL communications. (e.g. {@literal JKS}, {@literal PKCS11}, etc.)$$ *($$String$$, default: `$$JKS$$`)*
$$gemfire.security.ssl.keystore-uri$$:: $$Location of the pre-created {@literal Keystore} URI to be used for connecting to the Geode cluster$$ *($$Resource$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.ssl-keystore-password$$:: $$Password for accessing the keys truststore$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.ssl-truststore-password$$:: $$Password for accessing the trust store$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.truststore-type$$:: $$Identifies the type of truststore used for SSL communications. (e.g. {@literal JKS}, {@literal PKCS11}, etc.)$$ *($$String$$, default: `$$JKS$$`)*
$$gemfire.security.ssl.truststore-uri$$:: $$Location of the pre-created truststore URI to be used for connecting to the Geode cluster$$ *($$Resource$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.user-home-directory$$:: $$Local directory to store the truststore and keystore files copied form the remote truststoreUri and getKeystoreUri uris.$$ *($$String$$, default: `$$user.home$$`)*
$$gemfire.security.username$$:: $$The cache username.$$ *($$String$$, default: `$$<none>$$`)*
//end::configuration-properties[]

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar gemfire-sink.jar --gemfire.keyExpression=
```

//end::ref-doc[]
