//tag::ref-doc[]
= Gemfire Source

This source allows you to subscribe to any creates or updates to a Gemfire region.  The application configures a client cache and client region, along with the necessary
subscriptions enabled. By default the payload contains the updated entry value,
but may be controlled by passing in a SpEL expression that uses the EntryEvent as the
evaluation context.

== Input

N/A

== Output

=== Headers

* `content-type: text/plain`

=== Payload

* `String`

== Options

The **$$gemfire$$** $$source$$ supports the following configuration properties:

//tag::configuration-properties[]
$$gemfire.cache-event-expression$$:: $$SpEL expression to extract fields from a cache event.$$ *($$Expression$$, default: `$$<none>$$`)*
$$gemfire.pool.connect-type$$:: $$Specifies connection type: 'server' or 'locator'.$$ *($$ConnectType$$, default: `$$<none>$$`, possible values: `locator`,`server`)*
$$gemfire.pool.host-addresses$$:: $$Specifies one or more Gemfire locator or server addresses formatted as [host]:[port].$$ *($$InetSocketAddress[]$$, default: `$$<none>$$`)*
$$gemfire.pool.subscription-enabled$$:: $$Set to true to enable subscriptions for the client pool. Required to sync updates to the client cache.$$ *($$Boolean$$, default: `$$false$$`)*
$$gemfire.region.region-name$$:: $$The region name.$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.password$$:: $$The cache password.$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.ssl-keystore-password$$:: $$Password for accessing the keys truststore$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.ssl-truststore-password$$:: $$Password for accessing the trust store$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.store-file-name$$:: $$Name of the trust store file copied in the local file system.$$ *($$String$$, default: `$$trusted.keystore$$`)*
$$gemfire.security.ssl.truststore-uri$$:: $$Location of the pre-created truststore file to be used for connecting to the Geode cluster$$ *($$Resource$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.user-home-directory$$:: $$Local location to copy the trust store file.$$ *($$String$$, default: `$$user.home$$`)*
$$gemfire.security.username$$:: $$The cache username.$$ *($$String$$, default: `$$<none>$$`)*
//end::configuration-properties[]

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar ./gemfire-source.jar --gemfire.region.region-name=MyRegion --gemfire.cacheEventExpression="newValue"
```

//end::ref-doc[]
