//tag::ref-doc[]
= Gemfire Source

This source allows you to subscribe to any creates or updates to a Gemfire region.  The application configures a client cache and client region, along with the necessary
subscriptions enabled. By default the payload contains the updated entry value,
but may be controlled by passing in a SpEL expression that uses the EntryEvent as the
evaluation context.

To enable SSL communication between Geode Source and the Geode cluster you need to provide the URIs of the
Keystore and Truststore files using the `gemfire.security.ssl.keystore-uri` and `gemfire.security.ssl.truststore-uri` properties.
(If a single file is ued for both stores then point both URIs to it).

== Input

N/A

== Output

=== Headers

* `content-type: text/plain`

=== Payload

* `String`

== Options

The **$$gemfire$$** $$source$$ supports the following configuration properties:

//tag::configuration-properties[]
$$gemfire.cache-event-expression$$:: $$SpEL expression to extract fields from a cache event.$$ *($$Expression$$, default: `$$<none>$$`)*
$$gemfire.pool.connect-type$$:: $$Specifies connection type: 'server' or 'locator'.$$ *($$ConnectType$$, default: `$$<none>$$`, possible values: `locator`,`server`)*
$$gemfire.pool.host-addresses$$:: $$Specifies one or more Gemfire locator or server addresses formatted as [host]:[port].$$ *($$InetSocketAddress[]$$, default: `$$<none>$$`)*
$$gemfire.pool.subscription-enabled$$:: $$Set to true to enable subscriptions for the client pool. Required to sync updates to the client cache.$$ *($$Boolean$$, default: `$$false$$`)*
$$gemfire.region.region-name$$:: $$The region name.$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.password$$:: $$The cache password.$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.ciphers$$:: $$Configures the SSL ciphers used for secure Socket connections as an array of valid cipher names.$$ *($$String$$, default: `$$any$$`)*
$$gemfire.security.ssl.keystore-type$$:: $$Identifies the type of Keystore used for SSL communications (e.g. JKS, PKCS11, etc.).$$ *($$String$$, default: `$$JKS$$`)*
$$gemfire.security.ssl.keystore-uri$$:: $$Location of the pre-created Keystore URI to be used for connecting to the Geode cluster.$$ *($$Resource$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.ssl-keystore-password$$:: $$Password for accessing the keys truststore$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.ssl-truststore-password$$:: $$Password for accessing the trust store.$$ *($$String$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.truststore-type$$:: $$Identifies the type of truststore used for SSL communications (e.g. JKS, PKCS11, etc.).$$ *($$String$$, default: `$$JKS$$`)*
$$gemfire.security.ssl.truststore-uri$$:: $$Location of the pre-created truststore URI to be used for connecting to the Geode cluster.$$ *($$Resource$$, default: `$$<none>$$`)*
$$gemfire.security.ssl.user-home-directory$$:: $$Local directory to cache the truststore and keystore files downloaded form the truststoreUri and keystoreUri locations.$$ *($$String$$, default: `$$user.home$$`)*
$$gemfire.security.username$$:: $$The cache username.$$ *($$String$$, default: `$$<none>$$`)*
//end::configuration-properties[]

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar ./gemfire-source.jar --gemfire.region.region-name=MyRegion --gemfire.cacheEventExpression="newValue"
```

//end::ref-doc[]
