//tag::ref-doc[]
= Gemfire Source

This source allows you to subscribe to any creates or updates to a Gemfire region.  The application configures a client cache and client region, along with the necessary
subscriptions enabled. By default the payload contains the updated entry value,
but may be controlled by passing in a SpEL expression that uses the EntryEvent as the
evaluation context.

== Input

N/A

== Output

=== Headers

* `content-type: text/plain`

=== Payload

* `String`

== Options

The **$$gemfire$$** $$source$$ supports the following configuration properties:

//tag::configuration-properties[]
$$gemfire.cache-event-expression$$:: $$SpEL expression to extract fields from a cache event.$$ *($$Expression$$, default: `$$<none>$$`)*
$$gemfire.pool.connect-type$$:: $$Specifies connection type: 'server' or 'locator'.$$ *($$ConnectType$$, default: `$$<none>$$`, possible values: `locator`,`server`)*
$$gemfire.pool.host-addresses$$:: $$Specifies one or more Gemfire locator or server addresses formatted as [host]:[port].$$ *($$InetSocketAddress[]$$, default: `$$<none>$$`)*
$$gemfire.pool.subscription-enabled$$:: $$Set to true to enable subscriptions for the client pool. Required to sync updates to the client cache.$$ *($$Boolean$$, default: `$$false$$`)*
$$gemfire.region.region-name$$:: $$The region name.$$ *($$String$$, default: `$$<none>$$`)*
//end::configuration-properties[]

//end::ref-doc[]
== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar gemfire_source.jar --gemfire.cacheEventExpression=" "
```
